name: Deploy Vite/Vue to GitHub Pages

on:
    push:
        branches:
            - prd
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Build Project
              run: |
                  npm run build
                  cp dist/index.html dist/404.html

            - name: Deploy to GitHub Pages
              run: ./node_modules/.bin/gh-pages -d dist --repo https://x-access-token:${GITHUB_TOKEN}@github.com/Speakman610/byu-cs-music-capstone.git
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
