name: Deploy Vite/Vue to GitHub Pages

on:
    push:
        branches:
            - prd

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Configure Git User
              run: |
                git config --global user.email "github-actions@github.com"
                git config --global user.name "github-actions"

            - name: Deploy to GitHub Pages
              run: npm run deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
